services:
  frontend:
    build:
      context: .     # âœ… joriy papkani build kontekst deb oladi
      dockerfile: Dockerfile
    ports:
      - "13131:80"
    container_name: shpion_client
    restart: always
